### PR TITLE
return red border around invalid form fields

### PR DESCRIPTION
**Pull request by masonh**
addresses  #111

The 0-width border in this theme prevented the red error border from showing. This commit returns a 1px solid border with the same CSS selector as PVE's built-in theme and corrects for the corresponding layout disruption by adding a -1px margin. The built-in theme currently sets the border color to #cf4c35, which is not overridden.

image

### CODE REVIEW

**Comment by Weilbyte** [comment]
Thanks! Just one more thing before merge: please make sure your Sass compiler doesn't try to optimize the code (this has resulted in some odd things breaking in the past), but rather, just minify it.

**Comment by masonh** [comment]
The first compile was with ruby sass. I also tried sassc, which gets closer to yours but still converts some "-webkit" properties to the standard form and changes "top-background" (which I've never seen before) to "background". So I ended up copying the changed bit in by hand. Which sass compiler do you use?

**Comment by Weilbyte** [comment]
I use [this VSCode extension](https://marketplace.visualstudio.com/items?itemName=ritwickdey.live-sass), unsure what it uses under the hood.

**Comment by masonh** [comment]
I took a quick look and it appears to use libsass, which is also the library behind sassc. The libsass library has been deprecated and the extension you linked abandoned, so you may want to look into updating to [this newer fork](https://marketplace.visualstudio.com/items?itemName=glenn2223.live-sass) at some point.

**Pull request merged**
