### PR TITLE
Create UtilityUpdater.sh

### PR DESCRIPTION
**Pull request by RisedSky**
Permit to update the python file

### CODE REVIEW

**Comment by Weilbyte** [comment]
Could you rename the file to something like `UtilityUpdater.sh`?

**Comment by RisedSky** [comment]
@Weilbyte sure !

**Comment by RisedSky** [comment]
You'll be able to remove it in another commit, can't do it actually on phone

**Comment by RisedSky** [comment]
Fixed, you can pull

**Pull request merged**
